### ISSUE TITLE
Use real time and timezones

### ISSUE THREAD

**Issue by probonopd** [probonopd/ESP8266HueEmulator#9]
The original bridge has real time clock information and knows about timezones, allowing for timed events. Maybe we could use https://github.com/JChristensen/Timezone to do the same.

**Comment by probonopd** [comment]
This is needed e.g., for wake up timers which can be set from the app.

**Comment by ensonic** [comment]
Woulnd't it be easier to use
https://nodemcu.readthedocs.io/en/master/en/modules/sntp/

**Comment by probonopd** [comment]
Yes, if you assume there is Internet connectivity.

**Comment by ensonic** [comment]
Sorry for the noise, this was a js library. I'll try https://github.com/gmag11/NtpClient and send a PR.

**Comment by ensonic** [comment]
I have added NTP support and now send the time with the config request. I am testing with the All4Hue android app and it does not warning about this anymore.
For the timezone, we need to send a block like:
```
"timezone": "Europe/London",
```
with the config. Since the time is sent as utc localtime, we could also hardcode the timezone for now.

Apps like All4Hue can set the timezone on the bridge and once we have #53 fixed, we can store it and use it to correct the localtime. Does that make sense?

**Comment by probonopd** [comment]
Yes, PRs highly appreciated.
